name: Run tests

on:
  push:
    branches:
      - 'Deployment/Prod'
  pull_request:
    branches:
      - 'Deployment/Prod'

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
